import { type NextPage } from "next";
import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import Navbar from "../../../components/navbar/Navbar";
import { signIn, signOut, useSession } from "next-auth/react";
import Button, { ColorOptions } from "../../../components/buttons/Button";
import { useRouter } from "next/router";

import { api } from "../../../utils/api";
import { contextProps } from "@trpc/react-query/shared";

import { Listbox, Transition } from "@headlessui/react";
import Dialog from "./../../../components/dialogs/Dialog";
import Container from "../../../components/annonse/Container";
import Swiper from "../../../components/swiper/Swiper";
import { array, string } from "zod";
import { map } from "@trpc/server/observable";
import Ad from "../../../components/ad/Ad";
import { Advert } from "@prisma/client";

//Mangler bare å få henta ut favorittobjektene
//Har hentet ut hele tabellen, får ikke til å hente ut de adID på riktig bruker og så bruke det til å hente ut riktig advert

const Favoritter: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const ctx = api.useContext();

  // get id from nextjs router
  const { id } = router.query;

  // get advert by id
  const { data: adverts } = api.favorites.getByUser.useQuery(
    {
      id: id as string,
    },
    {
      enabled: !!id,
    }
  );
    let keys: string[] = []
    let titles: string[] = []
    let prices: number[] = []
    adverts?.map((ad) => {
        const { data: advert } = api.advertisement.getOne.useQuery({id: ad.advertId as string})
        if (!advert?.id || !advert?.title || !advert?.price) {
            return null;
        }
        keys.push(advert?.id)
        titles.push(advert?.title)
        prices.push(advert?.price)
    })

    //<Ad key={ad.id} title={ad.title} price={ad.price} id={ad.id} />

  /*let ads: Advert[];
  adverts?.map((ad) => {
    ads.push(api.advertisement.getOne.useQuery({id: ad.advertId as string}))
  });*/

  const { data : favorites }=api.advertisement.getAll.useQuery();
  const favoriteAds = api.advertisement

  

  return (
    <>
      <Head>
        <title>Toolhub | Annonser</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gray-100">
        <Navbar />
        <section className="mt-40 flex flex-col px-[120px]">
          <p className="font-futura text-2xl">
            Se gjennom <span className="text-emerald-700">dine favoritter</span>
          </p>
          <p className="font-futura text-md mt-10 text-gray-400">
            Du har {adverts?.length} favorittannonser
          </p>
          <div className="mt-5 flex max-w-full flex-row flex-wrap gap-[0.2rem]">
            {/* {for (let i = 0; i < keys.length; i++) {
            //     <Ad key={keys[i]} title={titles[i]} price={prices[i]} id={keys[i]} />
            // }} */}
          </div>
        </section>
      </main>
    </>
  );
};

export default Favoritter;